### ISSUE TITLE
i try it, has a exception

### ISSUE THREAD

**Issue by zaki2000** [MaruTama/tensorflow_for_unity#1]
DllNotFoundException: libtensorflow
TensorFlow.TFCore.get_Version () (at <84fe2dcd3ba246c39b3de0e995570f79>:0)

it needs some .dll or so .like this libtensorflow.so?
unity ver 2017.1.0f1
TensorFlowSharp.dll is in Assets\Dlls
i have no change any code

**Comment by zaki2000** [comment]
succeed, on windows, it needs libtensorflow.dll, isn't it

**Comment by MaruTama** [comment]
I had written the build method of TensorFlowSharp in each OS in README.

refer README setting up development environment and building TensorFlowSharp.

After build, Please copy TensorFlowSharp.dll and System.ValueTuple.dll under TensorFlowSharp/TensorFlowSharp/bin/Debug to Assets/Dlls.

I think that it will work.

I will write in detail how to create a CNN model and unity project.

**Comment by zaki2000** [comment]
Thank you MaruTama. I just mising [libtensorflow.dll] on [windows,unity2017], and it works well.
My model trained by tensor-flow python api.
Now I still have two questions.
Simply it is how to build to Android and how to use only one graph and [session] or [session runner] multiple [AddInput] and [Fetch], because I don't want to load graph every predict.
And I will open another issue.
